### PR TITLE
Change version

### PR DESCRIPTION
**Pull request by sajuptpm**
Append commit count and ref to version
Example: 2.1+3290+ca6b2ff

### CODE REVIEW

**Comment by MayankGo** [comment]
wait saju we need to think if we have any other  better option then this

**Comment by sajuptpm** [comment]
Test build triggered
contrail-gate/92/

**Comment by sajuptpm** [comment]
build 92 failed because of wrong contrail-third-party path
Triggered new build contrail-gate/93/

**Comment by sajuptpm** [comment]
Build success
puppet_rjil_pkg_test/147/

* Version of contrail-config Package from ct1
 
$ sudo apt-cache policy contrail-config
contrail-config:
  Installed: 2.1+4986+999644c
  Candidate: 2.1+4986+999644c
  Version table:
 *** 2.1+4986+999644c 0
        999 file:/var/lib/jiocloud/overrides/ ./ Packages
        100 /var/lib/dpkg/status
     1.21+3290+ca6b2ff 0
        500 http://jiocloud.rustedhalo.com/ubuntu/ trusty-testing/main amd64 Packages

**Pull request merged**
